workflows:
  android-workflow:
    name: Android Telegram Downloader Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    environment:
      android_signing:
        - telegram_downloader_keystore  # Optional: for signed APKs
      groups:
        - telegram_credentials  # Add your API credentials here
      vars:
        PACKAGE_NAME: "com.telegramdownloader"
      node: 16.20.0
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
      cancel_previous_builds: true
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Set up environment variables
        script: |
          # Environment variables are automatically available from Codemagic
          echo "Building with API credentials from environment"
      
      - name: Build Android Release APK
        script: |
          cd android
          ./gradlew assembleRelease
    
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    
    publishing:
      email:
        recipients:
          - your-email@example.com  # Change this to your email
        notify:
          success: true
          failure: true
